# Generated by Django 4.2.6 on 2023-12-23 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_rename_modelo_auto_auto_rename_patent_auto_patente'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(choices=[('CAM', 'Cambiar Aceite Motor'), ('RPF', 'Revisar Pastilla Freno'), ('ACC', 'Ajuste Caja Cambio')], max_length=3)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('fecha_ingreso', models.DateField(null=True)),
                ('fecha_salida', models.DateField(null=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('protocolo_servicio', models.CharField(blank=True, max_length=32, null=True)),
                ('categoria_mantenimiento', models.ManyToManyField(to='servicios.categoriamantenimiento')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
            ],
        ),
    ]
