# Generated by Django 4.2.6 on 2023-12-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='protocolo_servicio',
            field=models.CharField(blank=True, max_length=52, null=True),
        ),
    ]
