# Generated by Django 4.2.6 on 2023-12-02 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='modelo',
            new_name='auto',
        ),
        migrations.RenameField(
            model_name='auto',
            old_name='patent',
            new_name='patente',
        ),
    ]
